### ISSUE TITLE
有关于model

### ISSUE THREAD

**Issue by Cooper111** [zle1992/atec#2]
你好，复现的时候发现只能跑通esim和cnn（这两个模型的输入为**5个**），其他模型（输入为**3个**）跑不通。
尝试更改config.py里的data_augument参数来调整为3输入，可是其他模型都报错，类似
`ValueError: Error when checking target: expected dense_7 to have shape (None, 2) but got array with shape (31500, 1)`

**Comment by zle1992** [comment]
> 你好，复现的时候发现只能跑通esim和cnn（这两个模型的输入为**5个**），其他模型（输入为**3个**）跑不通。
> 尝试更改config.py里的data_augument参数来调整为3输入，可是其他模型都报错，类似
> `ValueError: Error when checking target: expected dense_7 to have shape (None, 2) but got array with shape (31500, 1)`


esim cnn 最后一层是 pred = Dense(1, activation='sigmoid')(x)
其他的模型是Dense(2),把都改成dense(1)就行了
